include ../suite.mk

programs := blackscholes bodytrack facesim ferret freqmine raytrace swaptions
programs += fluidanimate vips x264 canneal dedup streamcluster

all: $(programs)

$(eval $(call declare_suite,parsec,$(programs)))
