include ../suite.mk

benchmarks := \
	blackscholes bodytrack canneal dedup facesim ferret fluidanimate freqmine \
	raytrace streamcluster swaptions vips x264

$(eval $(call declare_suite,parsec,$(benchmarks)))
