include ../suite.mk

benchmarks := \
	GemsFDTD astar bwaves bzip2 cactusADM calculix dealII gamess gcc gobmk \
	gromacs h264ref hmmer lbm leslie3d libquantum mcf milc namd omnetpp \
	perlbench povray sjeng soplex sphinx3 tonto wrf xalancbmk zeusmp

$(eval $(call declare_suite,cpu2006,$(benchmarks)))
